### ISSUE TITLE
Username changed, article author isn't updated

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#14]
Hi @AlexSheer,

if the username of an article author  is changed, the username isn't updated in KB:
- Original username:
![original_username](https://user-images.githubusercontent.com/7478287/31699308-8f0eca10-b3c2-11e7-9a6c-c57d003dee3a.jpg)

- after that the username was changed, the user published two new articles (GREEN), it's OK, but the old articles display the old username (ORANGE):
![username_changed](https://user-images.githubusercontent.com/7478287/31699417-4b8e2cbc-b3c3-11e7-9cb6-10af387c6eb7.jpg)

**Comment by AlexSheer** [comment]
https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/commit/55725032d1054c661a31b2d819ac9677cc9306ce#diff-ad9eff7f46914b507cec14531dfe6c62
