### ISSUE TITLE
Copy feature doesn’t work on Webkit browsers

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#17]
Hi @AlexSheer,

the new feature Copy (link)  doesn’t work on Webkit browsers (Chrome, Opera) while there isn’t any problem on Firefox.

**Comment by AlexSheer** [comment]
Fixed! https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/commit/db1cd3867c1ce2c06ffca263a2e8fd6ce11fd3b7#diff-70ffa6b5c0c35e9c17676fd7d34d115a
