### ISSUE TITLE
Description category is displayed only for main categories

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#18]
Hi @AlexSheer,

If I have this categories configuration:

- category A
  - sub-category 1
    - sub-sub-category a
- category B

on KB index page the descpription for category A is displayed correctly but if I enter in it, the description for sub-category 1 isn’t displayed.
Same issue if I enter in sub-category 1, the description for sub-sub-category  a isn’t showed.

**Comment by AlexSheer** [comment]
> description for sub-sub-category a isn’t showed.

That should be it. It's not a mistake. For this is superfluous.
