### ISSUE TITLE
Sub-categories link are incorrect

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#19]
Hi @AlexSheer,

If I have this categories configuration:

- category A
  - sub-category 1
    - sub-sub-category a
- category B

on KB index page the links to sub-categories “sub-category 1” and “sub-sub-category a” are correct, but if I enter in “category A”:
- the link to “sub-category 1” is **incorrect**, in fact it’s the same to “sub-sub-category a”
- the link to “sub-sub-category a” is **correct**,

**Comment by AlexSheer** [comment]
Fixed! https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/commit/bd8bf1bf7d3a34b34db7670734d8efc13f971508#diff-ad9eff7f46914b507cec14531dfe6c62
