### ISSUE TITLE
Search feature - Add the possibility to search in titles and descriptions

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#21]
Hi @AlexSheer,

could you add the possibility to search also in title and description, please?

**Comment by AlexSheer** [comment]
Done!

**Comment by Galixte** [comment]
Thanks a lot for adding the possibility to search in titles. If in a future you can add the possibility to search in description it could be useful, indeed I enter some unique words in descriptions, these we don’t find in article titles & texts. ;)

**Comment by Galixte** [comment]
@AlexSheer thanks for added description searches. ;)
