### ISSUE TITLE
BLOCKER - “Can edit own articles” & “Can delete own articles” / Need To update language key

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#29]
Hi @AlexSheer,

simple users with the next permissions applied can’t delete or edit their articles: 
- “Can add article” set to YES
- “Can edit own articles” set to YES
- “Can delete own articles” set to YES
- “Can add articles without prior approval” whatever if it set to YES or NO

When they want to edit or delete their articles, the messages appear respectively:
- “You can not edit articles”
- “You can not delete articles”

---------------

So, in awaiting a fix from you, I authorized the “Moderative permissions”: 
- “Can edit articles”
- “Can delete articles”.

I realized that the permission “Can add articles without prior approval” has an impact also to edit permission.

If a user, can add, edit articles but doesn’t have the “Can add articles without prior approval” permission set to YES, his edit action is also submitted to approval.

So, I suggest to rename the  “Can add articles without prior approval” permission to:
```Can add / edit articles without prior approval```

Regards.

**Comment by Galixte** [comment]
Could you fix this important issue, please?

**Comment by AlexSheer** [comment]
It has been fixed for a long time. The error was that the permissions were checked at the wrong place in the script and not completely correct.

**Comment by Galixte** [comment]
Nice, thanks!
