### ISSUE TITLE
Error when guest try to access to the KB

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#30]
Hi @AlexSheer,

an error is displayed when guest try to access to KB:

```
phpBB Debug] PHP Warning: in file [ROOT]/ext/sheer/knowledgebase/inc/functions_kb.php on line 465: implode(): Invalid arguments passed

Erreur générale
SQL ERROR [ mysqli ]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 5 [1064]
```

**Comment by AlexSheer** [comment]
??? functions_kb.php on line 465 https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/blob/master/inc/functions_kb.php#L465

**Comment by Galixte** [comment]
Example here: http://www.techniarabia.com/knowledgebase

**Comment by AlexSheer** [comment]
@Galixte I guess that you delete Anonymous from the database, or delete it from all users groups. Run STK - SUPPORT TOOLS - Sanitise Anonymous User
But fix on this case here https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/commit/f21878006442a7fe4e309e876dbb704190513c40#diff-6649e448ac5c7d490bd996a521574785

**Comment by AlexSheer** [comment]
And I did not accidentally make a tool for checking users who have been deleted from all groups  yesterday

Special 4U LOL:

**Comment by Galixte** [comment]
It’s not my board, a user tested your extension and reported it to me.

The anonymous user was in no group, after added in guests groups it works fine, thanks for fixed it. ;)
