### ISSUE TITLE
EDIT action doesn’t keep the original category of the article

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpbb3.2-Knowledge-Base#32]
@AlexSheer,

when I edit an article, the drom down menu named “Category:” where there are the categories list doesn’t keep the category selected when I have created the article.

It’s reinitiated to the first choice of the categories list.

could you fix this, please?

**Comment by Galixte** [comment]
I note that is more problematic than I thought, the original choice is grayed, because this is ```disabled="disabled" class="disabled-option"``` is present in the option tag.

**Comment by Galixte** [comment]
In awaiting a patch I have removed: ``` disabled="disabled" class="disabled-option"``` from this line: https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/blob/master/inc/functions_kb.php#L237.

**Comment by AlexSheer** [comment]
Fixed!https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/commit/85ebedb3d74d0fed257bb14f803d1995e7328b3d#diff-8a628c06f2fdc9acb52694f411bb6a2c

**Comment by Galixte** [comment]
Thanks!
