### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Defra89** [AlexSheer/phpbb3.2-Knowledge-Base#34]
hi there i downloaded the zip.
unpacked and uploaded to root/ext but it does not appear in my extension list to activate it 
how do i get this ext running it looks like it has the features like sorting the article's i was looking for

**Comment by AlexSheer** [comment]
As usual https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/blob/master/README.md
+ https://www.phpbb.com/extensions/installing/
