### ISSUE TITLE
General Error

### ISSUE THREAD

**Issue by wlh1950** [AlexSheer/phpbb3.2-Knowledge-Base#43]
I get the following error when I use the search function:

General Error
SQL ERROR [ mysqli ]

Unknown column 'm1.post_id' in 'where clause' [1054]

SQL

SELECT p.article_id FROM (phpbb_kb_src_wrdmtch m1 CROSS JOIN phpbb_kb_src_wrdmtch m2 CROSS JOIN phpbb_kb_src_wrdmtch m3 CROSS JOIN phpbb_kb_src_wrdmtch m4 CROSS JOIN phpbb_kb_src_wrdmtch m0) LEFT JOIN phpbb_kb_articles p ON (m0.article_id = p.article_id) WHERE m0.word_id = 4961 AND m1.word_id = 4638 AND m1.post_id = m0.post_id AND m2.word_id = 76 AND m2.post_id = m0.post_id AND m3.word_id = 32 AND m3.post_id = m0.post_id AND m4.word_id = 102 AND m4.post_id = m0.post_id AND p.approved= 1 GROUP BY p.article_id, article_date ORDER BY article_date DESC LIMIT 250

BACKTRACE

**Comment by rxu** [comment]
I guess that should be it: in https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/blob/master/search/kb_fulltext_native.php replace all occurrences of `post_id` with `article_id` (I've been able to find 6).
Not tested though.

**Comment by wlh1950** [comment]
tested and solved
